filter:
  include_entities:
    - switch.desk_lamp_switch
    - switch.office_light_switch
    - light.living_room_lights
    - light.family_room_lights_level
    - media_player.family_room_tv
    - light.bedroom_lights
    - switch.kitchen_lights
    - switch.bathroom_vanity
    - switch.bathroom_fan
    
entity_config:
  switch.desk_lamp_switch:
    name: Desk Lamp
    display_categories: LIGHT
  switch.office_light_switch:
    name: Office Light
    display_categories: LIGHT
  light.family_room_lights:
    name: Family Room Lights
    display_categories: LIGHT
  media_player.family_room_tv:
    name: Family Room TV
    display_categories: TV
  light.living_room_lights:
    name: Living Room Lights
    display_categories: LIGHT
  light.bedroom_lights:
    name: Bedroom Lights
    display_categories: LIGHT
  switch.kitchen_lights:
    name: Kitchen Lights
    display_categories: LIGHT
  switch.bathroom_vanity:
    name: Bathroom Light
    display_categories: LIGHT
  switch.bathroom_fan:
    name: Bathroom Fan
    display_categories: LIGHT

