filter:
  include_entities:
    - switch.desk_lamp_switch
    - switch.office_light_switch
    - light.living_room_lights
    - light.family_room_lights
    - media_player.family_room_tv
    - light.bedroom_lights
    - switch.kitchen_lights
    - switch.bathroom_vanity
    - switch.bathroom_fan
    - script.lights_off
    - switch.patio_lights
    - switch.front_door_lights
    - switch.utility_room_light
    - input_boolean.living_room_tv
    - input_boolean.bedroom_tv
    - switch.family_room_fan
    
entity_config:
  switch.desk_lamp_switch:
    name: Desk Lamp
    display_categories: LIGHT
  switch.office_light_switch:
    name: Office Light
    display_categories: LIGHT
  light.family_room_lights:
    name: Family Room Lights
    display_categories: LIGHT
  media_player.family_room_tv:
    name: Family Room TV
    display_categories: TV
  light.living_room_lights:
    name: Living Room Lights
    display_categories: LIGHT
  light.bedroom_lights:
    name: Bedroom Lights
    display_categories: LIGHT
  switch.kitchen_lights:
    name: Kitchen Lights
    display_categories: LIGHT
  switch.bathroom_vanity:
    name: Bathroom Light
    display_categories: LIGHT
  switch.bathroom_fan:
    name: Bathroom Fan
    display_categories: LIGHT
  script.lights_off:
    name: Bedtime
    display_categories: SCENE_TRIGGER
  switch.patio_lights:
    name: Patio Lights
    display_categories: LIGHT
  switch.front_door_lights:
    name: Front Door Lights
    display_categories: LIGHT
  switch.utility_room_light:
    name: Utility Room Lights
    display_categories: LIGHT
  input_boolean.living_room_tv:
    name: Living Room TV
    display_categories: TV
  input_boolean.bedroom_tv:
    name: Bedroom TV
    display_categories: TV
  switch.family_room_fan:
    name: Family Room
    display_categories: SWITCH