homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:


http:
  api_password: !secret http_password
  ssl_certificate: !secret cert_path
  ssl_key: !secret key_path
  base_url: !secret url
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
   - apple_tv
   - samsung_tv
   - roku
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor:
  - platform: yr
    name: "Outside"
    monitored_conditions:
      - temperature
      - symbol
  - platform: mqtt
    name: "Kitchen Temperature"
    state_topic: "smartthings/Kitchen Motion Sensor/temperature"
  - platform: mqtt
    name: "Garage Temperature"
    state_topic: "smartthings/Garage Temperature/temperature"

    
# Text to speech
tts:
  - platform: google

#nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Cloud
cloud:
  alexa: !include alexa_config.yaml


# track phones 
device_tracker:

ios:

media_player:
  - platform: webostv
    host: 192.168.1.12
    name: Family Room TV
    timeout: 5
    filename: webostv.conf

camera:
  - platform: foscam
    ip: 192.168.1.22
    username: steve
    password: !secret foscam_password
    name: Front Door

mqtt:
  broker: 192.168.1.8

zwave:
  usb_path: /dev/ttyUSB0
  # add refresh delays for the GE dimmers
  device_config:
    light.living_room_lights: 
      refresh_value: true
      delay: 2
    light.family_room_lights:
      refresh_value: 2
      delay: 2
    light.bedroom_lights:
      refresh_value: 2
      delay: 2
#zigbee
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db
  

binary_sensor:
  # MQTT Motion Sensors from SmartThings MQTT Bridge
  - platform: mqtt
    name: "Kitchen Motion"
    state_topic: "smartthings/Kitchen Motion Sensor/motion"
    payload_on: "active"
    payload_off: "inactive"
  - platform: mqtt
    name: "Office Motion"
    state_topic: "smartthings/Office Motion Sensor/motion"
    payload_on: "active"
    payload_off: "inactive"

    
# Set up the garage doors from SmartThings MQTT bridge    
cover:
  - platform: mqtt
    name: "Right Garage Door"
    state_topic: "smartthings/Right Garage Door/contact"
    command_topic: "smartthings/Right Garage Door/door"
    state_open: 'open'
    state_closed: 'closed'
    payload_open: 'open'
    payload_close: 'closed'
    retain: true
    optimistic: true
  - platform: mqtt
    name: "Left Garage Door"
    state_topic: "smartthings/Left Garage Door/contact"
    command_topic: "smartthings/Left Garage Door/door"
    state_open: 'open'
    state_closed: 'closed'
    payload_open: 'open'
    payload_close: 'closed'
    retain: true
    optimistic: true

remote:
  - platform: harmony
    name: Family Room
    activity: AppleTV
  - platform: harmony
    name: Bedroom Hub
    activity: Watch Bedroom TV
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
