homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  whitelist_external_dirs:
    - /config/

logger:
  default: warn

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  radius: 100

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Set up security
http:
  api_password: !secret http_password
  #ssl_certificate: !secret cert_path
  #ssl_key: !secret key_path
  base_url: !secret url
  use_x_forwarded_for: true

# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
# discovery:
#   ignore:
#    - apple_tv
#    - samsung_tv
#    - roku

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enable the recorder
recorder:
  purge_keep_days: 10   # how many days to keep
  purge_interval: 1     # how often (in days) to purge old data


# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

python_script:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


mqtt:
  broker: 192.168.1.8
  client_id: homeassistant


# Text to speech
tts:
  - platform: google

#nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Cloud
cloud:
  alexa: !include alexa_config.yaml

# track phones
device_tracker:

# iOS Support
ios:

# Wake On Lan Support
wake_on_lan:

# Some input booeleans as flags for some automations
input_boolean:
  left_garage_auto_open:
    name: Left Garage Auto-Open
    icon: mdi:home-automation
  right_garage_auto_open:
    name: Right Garage Auto-Open
    icon: mdi:home-automation
  living_room_tv:
    name: Living Room TV
    icon: mdi:television
  bedroom_tv:
    name: Bedroom TV
    icon: mdi:television
  automation_debug:
    name: Automation
    icon: mdi:bug
    initial: off
  mqtt_debug:
    name: MQTT
    icon: mdi:bug
    initial: off
  python_script_debug:
    name: Python Scripts
    icon: mdi:bug
    initial: off
  device_tracker_debug:
    name: Device Tracker
    icon: mdi:bug
    initial: off

# Sensors
sensor:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    pws_id: KCASTUDI18
    monitored_conditions:
      - temp_f
      - weather_1d
  - platform: mqtt
    name: "Garage Temperature"
    state_topic: "garage/temperature"
    unit_of_measurement: '째F'
    value_template: "{{ value|round(1)}}"
  - platform: mqtt
    name: "Garage Humidity"
    state_topic: "garage/humidity"
    unit_of_measurement: '%'
    value_template: "{{ value|round(1) }}"
  # - platform: mqtt
  #   name: "Garage RSSI"
  #   state_topic: "garage/rssi"
  #   unit_of_measurement: 'dBm'
  #   value_template: "{{ '%i'|format(float(value)) }}"
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
    scan_interval: 1200
  - platform: cert_expiry
    host: hass.stevesell.com
    port: 443
    name: SSL Cert Expires
  - platform: template
    sensors:
      apartment_temperature:
        friendly_name: "Apartment Temperature"
        unit_of_measurement: '째F'
        value_template: >
          {% if states.sensor.apartment_motion_temperature.state %}
            {{ states.sensor.apartment_motion_temperature.state|int('-') }}
          {% else %}
            -
          {% endif %}
      house_power:
        friendly_name: House Power
        unit_of_measurement: 'W'
        value_template: >
          {% if states.sensor.energy_meter_power_4.state %}
            {{ states.sensor.energy_meter_power_4.state|int('-') }}
          {% else %}
            -
          {% endif %}
      kitchen_temperature:
        friendly_name: "Kitchen Temperature"
        unit_of_measurement: '째F'
        value_template: "{{ states.sensor.kitchen_motion_temperature.state|int('-') }}"
      office_temperature:
        friendly_name: "Office Temperature"
        unit_of_measurement: '째F'
        value_template: "{{ states.sensor.office_motion_temperature.state|int('-') }}"
      laundry_smoke_co_alarm:
        friendly_name: "Laundry Smoke Detector"
        value_template: >-
            {%- if is_state("sensor.alarm_type", "13") %}
                Idle
            {%- elif is_state("sensor.alarm_type", "1") %}
                Smoke Detected
            {%- elif is_state("sensor.alarm_type", "2") %}
                Carbon Monoxide Detected
            {%- elif is_state("sensor.alarm_type", "12") %}
                Alarm Testing
            {% else %}
                Unknown
            {%- endif %}
      bedroom_smoke_alarm:
        friendly_name: "Bedroom Smoke Detector"
        value_template: >-
            {%- if is_state("sensor.alarm_type_2", "13") %}
                Idle
            {%- elif is_state("sensor.alarm_type_2", "1") %}
                Smoke Detected
            {%- elif is_state("sensor.alarm_type_2", "2") %}
                Carbon Monoxide Detected
            {%- elif is_state("sensor.alarm_type_2", "12") %}
                Alarm Testing
            {% else %}
                Unknown
            {%- endif %}
      laundry_laundry_smoke_co_alarm_battery:
        value_template: >
          {% if states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector.state %}
            {{states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector.attributes.battery_level}}
          {% else %}
            n/a
          {% endif %}
        friendly_name: 'Laundry Smoke/CO Alarm Battery'
        unit_of_measurement: '%'
      bedroom_smoke_alarm_battery:
        value_template: >
          {% if states.zwave.first_alert_unknown_type0001_id0001.state %}
            {{states.zwave.first_alert_unknown_type0001_id0001.attributes.battery_level}}
          {% else %}
            n/a
          {% endif %}
        friendly_name: 'Bedroom Smoke Alarm Battery'
        unit_of_measurement: '%'

# Media Player Definitions
media_player:
  - platform: webostv
    host: 192.168.1.12
    name: Family Room TV
    timeout: 5
    filename: webostv.conf
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 38:8C:50:DC:DE:A4
    customize:
      sources:
        - HDMI1
        - HDMI2
  - platform: roku
    host: 192.168.1.13
    name: Family Room Roku


# Set up the Harmony Remotes
remote:
  - platform: harmony
    host: 192.168.1.15
    name: Family Room
    activity: AppleTV
  - platform: harmony
    host: 192.168.1.14
    name: Bedroom Hub
    activity: Watch Bedroom TV

# Camera Supprt
camera:
  - platform: foscam
    ip: 192.168.1.22
    username: steve
    password: !secret foscam_password
    name: Front Door

# Set up Z-Wave
zwave:
  usb_path: /dev/ttyUSB0
  # add refresh delays for the GE dimmers
  device_config:
    light.living_room_lights:
      refresh_value: true
      delay: 2
    light.family_room_lights:
      refresh_value: 2
      delay: 2
    light.bedroom_lights:
      refresh_value: 2
      delay: 2

#zigbee
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

# Set up the garage doors from SmartThings MQTT bridge
cover:
  - platform: mqtt
    name: "Right Garage Door"
    state_topic: "garage/rightDoor"
    command_topic: "garage/rightDoor/cmd"
    state_open: 'open'
    state_closed: 'closed'
    payload_open: 'open'
    payload_close: 'close'
    retain: false
    optimistic: true
    qos: 1
  - platform: mqtt
    name: "Left Garage Door"
    state_topic: "garage/leftDoor"
    command_topic: "garage/leftDoor/cmd"
    state_open: 'open'
    state_closed: 'closed'
    payload_open: 'open'
    payload_close: 'close'
    retain: false
    optimistic: true
    qos: 1


# My Split out configuration
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
