homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  elevation: !secret ele
  unit_system: imperial
  time_zone: America/Los_Angeles
  
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  whitelist_external_dirs:
    - /config/

  packages: !include_dir_named packages

logger:
  default: warn
  # logs:
  #   homeassistant.components.zha: debug
  #   bellows.zigbee.application: debug
  #   bellows: debug
  #   zigpy: debug

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  radius: 100

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Set up security
http:
  api_password: !secret http_password
  base_url: !secret url
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true


# Enable the recorder
recorder:
  purge_keep_days: 10   # how many days to keep
  purge_interval: 1     # how often (in days) to purge old data


# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enagble the Python Script component
python_script:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# weather
weather:
  - platform: yweather

# MQTT support 
mqtt:
  broker: 192.168.1.8
  client_id: homeassistant

#nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Cloud
# cloud:
#  alexa: !include alexa_config.yaml

# track phones
device_tracker:

# iOS Support
ios:
  push:
    categories:
      - name: Garage Door Open
        identifier: 'garagedoor'
        actions:
          - identifier: 'CLOSE_GARAGE_DOOR'
            title: 'Close Door'
            activationMode: 'background'


# Wake On Lan Support
wake_on_lan:

# downloader
downloader:
  download_dir: downloads



switch:
  - platform: wake_on_lan
    mac_address: "1C-1B-0D-9D-09-EC"
    name: "Raptor"
    host: 192.168.1.3


history_graph:
  house_power:
    name: House Power
    entities:
      - sensor.house_power
  garage_temperature:
    name: Garage Temperature
    entities:
      - sensor.garage_temperature
  apartment_temperature:
    name: Apartment Temperature
    entities:
      - sensor.apartment_temperature

# Some input booeleans as flags for some automations
input_boolean:
  automation_debug:
    name: Automation
    icon: mdi:bug
    initial: off
  mqtt_debug:
    name: MQTT
    icon: mdi:bug
    initial: off
  python_script_debug:
    name: Python Scripts
    icon: mdi:bug
    initial: off
  device_tracker_debug:
    name: Device Tracker
    icon: mdi:bug
    initial: off
  zigbee_debug:
    name: ZigBee
    icon: mdi:bug
    initial: off
  vacation_mode:
    name: Vacation Mode
    icon: mdi:beach
    


# Sensors
sensor:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    pws_id: KCASTUDI18
    monitored_conditions:
      - temp_f
      - weather_1d
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
    scan_interval: 1200
  - platform: cert_expiry
    host: hass.stevesell.com
    name: Server Cert Expires
  - platform: cert_expiry
    host: router.stevesell.com
    name: Router Cert Expires
  - platform: template
    sensors:
      apartment_temperature:
        friendly_name: "Apartment Temperature"
        unit_of_measurement: '°F'
        value_template: >
          {% if states.sensor.apartment_motion_temperature.state %}
            {{ states.sensor.apartment_motion_temperature.state|int('-') }}
          {% else %}
            -
          {% endif %}
      house_power:
        friendly_name: House Power
        unit_of_measurement: 'W'
        value_template: >
          {% if states.sensor.energy_meter_power_4.state %}
            {{ states.sensor.energy_meter_power_4.state|int('-') }}
          {% else %}
            -
          {% endif %}
      # kitchen_temperature:
      #   friendly_name: "Kitchen Temperature"
      #   unit_of_measurement: '°F'
      #   value_template: "{{ states.sensor.kitchen_motion_temperature.state|int('-') }}"
      # office_temperature:
      #   friendly_name: "Office Temperature"
      #   unit_of_measurement: '°F'
      #   value_template: "{{ states.sensor.office_motion_temperature.state|int('-') }}"
binary_sensor:
  - platform: template
    sensors:
      office_motion:
        friendly_name: Office Motion
        entity_id: sensor.office_motion_sensor_alarm_level
        value_template: "{{ is_state('sensor.office_motion_sensor_alarm_level', '255') }}"
        device_class: motion
      kitchen_motion:
        friendly_name: Kitchen Motion
        entity_id: sensor.kitchen_motion_sensor_alarm_level
        value_template: "{{ is_state('sensor.kitchen_motion_sensor_alarm_level', '255') }}"
        device_class: motion
      bedroom_outside_door:
        friendly_name: Bedroom Outside Door Sensor
        entity_id: sensor.hank_hkzwdws01_doorwindow_sensor_access_control
        value_template: "{{ is_state('sensor.hank_hkzwdws01_doorwindow_sensor_access_control','22') }}"
        device_class: door
      guest_motion:
        friendly_name: Guest Motion
        entity_id: sensor.guest_room_motion_sensor_alarm_level
        value_template: "{{ is_state('sensor.guest_room_motion_sensor_alarm_level', '255') }}"
        device_class: motion

# Enable FFMPEG component (needed for camera)
ffmpeg:

# Camera Support
camera:
  - platform: ring
  - platform: ffmpeg
    name: Front Door
    input: !secret front_door_cam_url
    extra_arguments: -vf "transpose=1"

#custom_updater
custom_updater:
  show_installable: false
  hide_sensor: true
  track:
    - components
    - cards
    - python_scripts

# Set up Z-Wave
zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key
  # add refresh delays for the GE dimmers
  device_config:
    light.living_room_lights:
      refresh_value: true
      delay: 2
    light.family_room_lights:
      refresh_value: true
      delay: 2
    light.bedroom_lights:
      refresh_value: true
      delay: 2

#zigbee
# zha:
#   usb_path: /dev/ttyUSB1
#   database_path: /config/zigbee.db


# My Split out configuration
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
