title: Airie and Steve's House
# Exclude entites from "Unused entities" view
excluded_entities:


views:
  # Main tab that will open first
  - icon: mdi:home-assistant
    title: Main
    cards:
      - type: picture-glance
        title: Office
        image: https://cdn.decoist.com/wp-content/uploads/2012/07/natural-walnut-home-office-furniture.jpg
        entities:
          - sensor.office_motion_sensor_temperature
          - binary_sensor.office_motion
          - entity: switch.office_light_switch
            icon: mdi:lightbulb
          - entity: switch.desk_lamp_switch
            icon: mdi:desk-lamp

  # Tab for all things climate control
  - title: Climate
    icon: mdi:weather-sunny
    id: climate
    cards:
      - type: entities
        title: Thermostat
        entities:
          - climate.family_room
          - sensor.family_room_thermostat_humidity
          - sensor.family_room_thermostat_hvac_state
          - binary_sensor.home_away
          - binary_sensor.family_room_thermostat_online

      - type: weather-forecast
        entity: weather.yweather
      
      - type: history-graph
        title: 'House Temperature'
        entities:
          - sensor.pws_temp_f
          - climate.family_room

      - type: history-graph
        title: 'Garage Conditions'
        entities:
          - sensor.garage_temperature
          - sensor.garage_humidity

      - type: history-graph
        title: 'Apartment Conditions'
        entities:
          - sensor.apartment_temperature