- alias: Door Alarm When Away
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.attic_door
        - binary_sensor.front_door
        - binary_sensor.kitchen_door
        - binary_sensor.bedroom_outside_door
        - binary_sensor.back_door
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: not_home
  action:
    - service: notify.ios_steves_iphone_x
      data_template:
        message: "{{ 'Alarm: ' + state_attr(trigger.entity_id,'friendly_name') }}"

- alias: Motion Alarm When Away
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.bedroom_motion
        - binary_sensor.family_room_motion
        - binary_sensor.kitchen_motion
        - binary_sensor.living_room_motion
        - binary_sensor.office_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: not_home
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
  action:
    - service: notify.ios_steves_iphone_x
      data_template:
        message: "{{ 'Alarm: ' + state_attr(trigger.entity_id,'friendly_name') }}"

- alias: Apartment Alarms
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.apartment_door
        - binary_sensor.apartment_motion
      to: 'on'
  action:
    - service: notify.ios_steves_iphone_x
      data_template:
        message: "{{ 'Alarm: ' + state_attr(trigger.entity_id,'friendly_name') }}"
