- alias: Attic Lights Auto-Off
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.attic_door
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.attic_light

- alias: Attic Lights Auto-On
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.attic_door
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.attic_light
