- alias: Fence Lights
  trigger:
    - platform: sun
      event: sunset
    - platform: sun
      event: sunrise
  action:
    - service_template: >
        {% if trigger.event=='sunset' %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.fence_lights
