- alias: Garage Welcome Lights
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_side_door
      from: 'off'
      to: 'on'
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
      service: script.timed_lights
      data_template:
        delay: '00:02:00'
        # pass a list of lights, rulling out the ones that are already on
        lights: >
          {{ [states.switch.garage_outside_light, 
                            states.switch.back_door_light] 
          | rejectattr('state','equalto','on')
          | map(attribute='entity_id' ) 
          | join(', ') }}
