### Steve's Garage Control

- alias: Right Auto Open Detect
  hide_entity: true
  trigger:
    - platform: state
      entity_id: device_tracker.steves_iphone_x
      to: 'not_home'
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.cover.right_garage_door.last_changed)) < 600 }}"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.right_garage_auto_open
    - service: notify.ios_steves_iphone_x
      data:
        message: "steve garage set"

- alias: Right Auto Open
  hide_entity: true
  trigger:
    - platform: state
      entity_id: device_tracker.steves_iphone_x
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.right_garage_auto_open
      state: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.right_garage_door
    - service: input_boolean.turn_off
      entity_id: input_boolean.right_garage_auto_open
    - service: notify.ios_steves_iphone_x
      data:
        message: "steve garage open"


### Airie's Garage Control

- alias: Left Auto Open Detect
  hide_entity: true
  trigger:
    - platform: state
      entity_id: device_tracker.airies_iphone_se
      to: 'not_home'
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.cover.left_garage_door.last_changed)) < 600 }}"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.left_garage_auto_open
    - service: notify.ios_steves_iphone_x
      data:
        message: "airie garage set"

- alias: Left Auto Open
  hide_entity: true
  trigger:
    - platform: state
      entity_id: device_tracker.airies_iphone_se
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.left_garage_auto_open
      state: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.left_garage_door
    - service: input_boolean.turn_off
      entity_id: input_boolean.left_garage_auto_open
    - service: notify.ios_steves_iphone_x
      data:
        message: "airie garage open"
