- alias: Away Actions
  hide_entity: true
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
  action:
    - service: climate.set_away_mode
      entity_id: climate.family_room
      data:
        away_mode: true
    - service: scene.turn_on
      entity_id: scene.bedtime
    - service: notify.ios_steves_iphone_x
      data:
        message: "Away"

- alias: Home
  hide_entity: true
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  action:
    - service: climate.set_away_mode
      entity_id: climate.family_room
      data:
        away_mode: false
    - service: notify.ios_steves_iphone_x
      data:
        message: "Home"
