- alias: House Welcome Lights
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_side_door
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: or  # 'when dark' condition: either after sunset or before sunrise
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
      - condition: template # One of us got home in the last 10 minutes
        value_template: "{{ (as_timestamp(now())-as_timestamp(states.group.family.last_changed)) < 600 }}"
  action:
      service: light.turn_on
      entity_id: light.family_room_lights
