- alias: Log Level
  trigger:
    platform: state
    entity_id: input_select.log_level
  action:
    service: logger.set_level
    data_template:
      "{{ states.input_select.which_component.state}}": "{{ trigger.to_state.state }}"
