- alias: Vacation Lights
  trigger:
    - platform: sun
      event: sunset
    - platform: time
      at: '22:45:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - service: notify.ios_steves_iphone_x
      data:
        message: "vacation_lights_triggered"
    - service_template: >
        {% if trigger.platform=='sun' %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id:
        - light.family_room_lights
        - light.living_room_lights
