- alias: Vacation Lights
  trigger:
    - platform: sun
      event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: not_home
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
  action:
    - service: light.turn_on
      entity_id:
        - light.family_room
        - light.living_room
    - delay: '02:45'
    - service: light.turn_off
      entity_id:
        - light.family_room
        - light.living_room
