alexa:
  smart_home:
    filter:
      include_entities:
        - switch.desk_lamp_switch
        - switch.office_light_switch
        - light.living_room_lights
        - light.family_room_lights
        - light.bedroom_lights
        - switch.kitchen_lights
        - switch.bathroom_vanity
        - switch.bathroom_fan
        - scene.bedtime
        - scene.gina_bedtime
        - scene.tv_time
        - switch.patio_lights
        - switch.front_door_lights
        - switch.utility_room_light
        - switch.living_room_tv
        - switch.bedroom_tv
        - switch.family_room_tv
        - switch.family_room_fan
        - switch.bedroom_fan
        - switch.dining_room_light
        - switch.back_door_light

    entity_config:
      switch.desk_lamp_switch:
        name: Desk Lamp
        display_categories: LIGHT
      switch.office_light_switch:
        name: Office Light
        display_categories: LIGHT
      light.family_room_lights:
        name: Family Room Lights
        display_categories: LIGHT
      switch.family_room_tv:
        name: Family Room TV
        display_categories: TV
      light.living_room_lights:
        name: Living Room Lights
        display_categories: LIGHT
      light.bedroom_lights:
        name: Bedroom Lights
        display_categories: LIGHT
      switch.kitchen_lights:
        name: Kitchen Lights
        display_categories: LIGHT
      switch.bathroom_vanity:
        name: Bathroom Light
        display_categories: LIGHT
      switch.bathroom_fan:
        name: Bathroom Fan
        display_categories: LIGHT
      scene.bedtime:
        name: Bedtime
        display_categories: SCENE_TRIGGER
      scene.gina_bedtime:
        name: Gina Bedtime
        display_categories: SCENE_TRIGGER
      scene.tv_time:
        name: TV Time
        display_categories: SCENE_TRIGGER
      switch.patio_lights:
        name: Patio Lights
        display_categories: LIGHT
      switch.front_door_lights:
        name: Front Door Lights
        display_categories: LIGHT
      switch.utility_room_light:
        name: Utility Room Lights
        display_categories: LIGHT
      switch.living_room_tv:
        name: Living Room TV
        display_categories: TV
      switch.bedroom_tv:
        name: Bedroom TV
        display_categories: TV
      switch.family_room_fan:
        name: Family Room Fan
        display_categories: SWITCH
      switch.bedroom_fan:
        name: Bedroom Fan
        display_categories: SWITCH
      switch.dining_room_light:
        name: Dining Room Light
        display_categories: LIGHT
      switch.back_door_light:
        name: Back Door Light
        display_categories: LIGHT
