input_number:
  slider1:
    name: Vol
    min: 0
    max: 60
    step: 1
  slider2:
    name: Vol
    min: 0
    max: 60
    step: 1
  slider3:
    name: Vol
    min: 0
    max: 60
    step: 1
  slider4:
    name: Vol
    min: 0
    max: 60
    step: 1
  slider5:
    name: Vol
    min: 0
    max: 60
    step: 1
  slider6:
    name: Vol
    min: 0
    max: 60
    step: 1

input_boolean:
  home_audio_zone_1:
    name: Family Room Speakers
    icon: mdi:speaker
  home_audio_zone_2:
    name: Kitchen Speakers
    icon: mdi:speaker
  home_audio_zone_3:
    name: Living Room Speakers
    icon: mdi:speaker
  home_audio_zone_4:
    name: Office Speakers
    icon: mdi:speaker
  home_audio_zone_5:
    name: Bedroom Speakers
    icon: mdi:speaker
  home_audio_zone_6:
    name: Patio Speakers
    icon: mdi:speaker
  home_audio_master_power:
    name: System Power
    icon: mdi:power

    
shell_command:
  home_audio_control: "python3 /config/command_line_scripts/home_audio_control.py -c {{command}} -z {{zone}} -v {{value}}"

group:
  home_audio:
    name: Home Audio System
    control: hidden
    entities:
      - input_boolean.home_audio_master_power
      - input_boolean.home_audio_zone_1
      - input_number.slider1
      - input_boolean.home_audio_zone_2
      - input_number.slider2
      - input_boolean.home_audio_zone_3
      - input_number.slider3
      - input_boolean.home_audio_zone_4
      - input_number.slider4
      - input_boolean.home_audio_zone_5
      - input_number.slider5
      - input_boolean.home_audio_zone_6
      - input_number.slider6

# Hide the "real" z-wave switch - the home_audio_master_power input_boolean is used instead
homeassistant:
  customize:
    switch.home_audio_system:
      hidden: true
      friendly_name: System Power
      icon: mdi:power

automation:
  - alias: Zone Volume Control
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - input_number.slider1
          - input_number.slider2
          - input_number.slider3
          - input_number.slider4
          - input_number.slider5
          - input_number.slider6
    condition:
      condition: template
      value_template: '{{ states("input_boolean.home_audio_zone_"+trigger.entity_id[-1])=="on" }}'
    action:
      - service: shell_command.home_audio_control
        data_template:
          command: "setvol"
          zone: "{{ trigger.entity_id[-1] }}"
          value: "{{ states(trigger.entity_id)|int }}"

  - alias: Zone Power Control
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - input_boolean.home_audio_zone_1
          - input_boolean.home_audio_zone_2
          - input_boolean.home_audio_zone_3
          - input_boolean.home_audio_zone_4
          - input_boolean.home_audio_zone_5
          - input_boolean.home_audio_zone_6
    condition:
      condition: state
      entity_id: switch.home_audio_system
      state: "on"
    action:
      - service: shell_command.home_audio_control
        data_template:
          command: "pwr"
          zone: "{{ trigger.entity_id[-1] }}"
          value: "{{ 0 if states(trigger.entity_id)=='off' else 1 }}"

  - alias: Zones off when power off
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_audio_master_power
        to: 'off'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id:
            - input_boolean.home_audio_zone_1
            - input_boolean.home_audio_zone_2
            - input_boolean.home_audio_zone_3
            - input_boolean.home_audio_zone_4
            - input_boolean.home_audio_zone_5
            - input_boolean.home_audio_zone_6
      - service: input_number.set_value
        data:
          entity_id:
            - input_number.slider1
            - input_number.slider2
            - input_number.slider3
            - input_number.slider4
            - input_number.slider5
            - input_number.slider6
          value: 0

  - alias: Home Audio Master Power On
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_audio_master_power
        to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.home_audio_system

  - alias: Home Audio Master Power Off
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_audio_master_power
        to: "off"
    action:
      - delay:
          seconds: 3 
      - service: switch.turn_off
        entity_id: switch.home_audio_system

    
