input_boolean:
  living_room_tv:
    name: Living Room TV
    icon: mdi:television
  family_room_tv:
    name: Family Room TV
    icon: mdi:television
  bedroom_tv:
    name: Bedroom TV
    icon: mdi:television
 
 # Media Player Definitions
media_player:
  - platform: webostv
    host: 192.168.1.12
    name: Family Room TV
    timeout: 5
    filename: webostv.conf
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 38:8C:50:DC:DE:A4
        broadcast_address: 192.168.1.255
    customize:
      sources:
        - HDMI1
        - HDMI2
  - platform: roku
    host: 192.168.1.13
    name: Family Room Roku


# Set up the Harmony Remotes
remote:
  - platform: harmony
    host: 192.168.1.15
    name: Family Room
    activity: AppleTV
  - platform: harmony
    host: 192.168.1.14
    name: Bedroom Hub
    activity: Watch Bedroom TV


automation:
  - alias: Living Room TV
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.living_room_tv
    action:
      - service_template: >
          {% if states.input_boolean.living_room_tv.state == 'on'  %}
            remote.turn_on
          {% else %}
            remote.turn_off
          {% endif %}
        entity_id: remote.family_room

  - alias: Bedroom TV
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.bedroom_tv
    action:
      - service_template: >
          {% if states.input_boolean.bedroom_tv.state == 'on'  %}
            remote.turn_on
          {% else %}
            remote.turn_off
          {% endif %}
        entity_id: remote.bedroom_hub

  - alias: Family Room TV Off
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.family_room_tv
        to: 'off'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.family_room_roku
          source: 'Home'
      - delay: '00:00:03'
      - service: media_player.turn_off
        entity_id: media_player.family_room_tv

  - alias: Family Room TV On
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.family_room_tv
        to: 'on'
    action:
      - service: media_player.turn_on
        entity_id: media_player.family_room_tv


  - alias: Set Input Boolean Living Room TV
    hide_entity: true
    trigger:
      - platform: state
        entity_id: remote.family_room
    action:
      - service_template: >
          {% if states.remote.family_room.state == 'on'  %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.living_room_tv

  - alias: Set Input Boolean Bedroom TV
    hide_entity: true
    trigger:
      - platform: state
        entity_id: remote.bedroom_hub
    action:
      - service_template: >
          {% if states.remote.bedroom_hub.state == 'on'  %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.bedroom_tv

  - alias: Set Input Boolean Family Room TV
    hide_entity: true
    trigger:
      - platform: state
        entity_id: media_player.family_room_tv
        from: 'off'
      - platform: state
        entity_id: media_player.family_room_tv
        to: 'off'
    action:
      - service_template: >
          {% if states.media_player.family_room_tv.state == 'off'  %}
            input_boolean.turn_off
          {% else %}
            input_boolean.turn_on
          {% endif %}
        entity_id: input_boolean.family_room_tv
